name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.PRIV_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.ADDR }} >> ~/.ssh/known_hosts
            ls

      - name: Deployment
        run: |
          ssh ${{ secrets.USR }}@${{ secrets.ADDR }} << 'EOF' 
          #! /bin/bash

            # Set working dir
            cd "$(dirname "$0")"

            # Variables
            REPO='https://github.com/bravevalley/HNG-fastapi-book-project.git'


        
            # Check if dir exist
            if [ -d HNG-fastapi-book-project/ ] ; then
                # rm if exist
                rm -rf HNG-fastapi-book-project/
            fi 

            # Stop and remove previously running Container/Images
            docker stop fastapi-app && docker rm fastapi-app
            docker rmi fastapi-app

            # clone repo
            git clone $REPO


            # Change workdir
            cd HNG-fastapi-book-project/

            # build image
            # run container
            docker build -t fastapi-app  . && docker run -dp  8000:8000 --name fastapi-app fastapi-app


          EOF
            